package model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseReserve<M extends BaseReserve<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer Id) {
		set("Id", Id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("Id");
	}

	public M setUseTime(java.lang.String useTime) {
		set("use_time", useTime);
		return (M)this;
	}
	
	public java.lang.String getUseTime() {
		return getStr("use_time");
	}

	public M setNum(java.lang.Integer num) {
		set("num", num);
		return (M)this;
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPhone(java.lang.Integer phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.Integer getPhone() {
		return getInt("phone");
	}

	public M setEmial(java.lang.String emial) {
		set("emial", emial);
		return (M)this;
	}
	
	public java.lang.String getEmial() {
		return getStr("emial");
	}

	public M setAddTime(java.lang.Integer addTime) {
		set("add_time", addTime);
		return (M)this;
	}
	
	public java.lang.Integer getAddTime() {
		return getInt("add_time");
	}

}
